### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by mimoun1997** [mimoun1997/robot#1]
## TODO
- [ ] Organitzar el joc amb plantilla ES6
- [ ] Sistema amb estats, Splash Screen, Menu, Joc (mínim dos nivells) i Game Over o similar
- [ ] Afegir una porta o punt final del nivell que porti a un altre nivell
- [ ] Mon amb plataformes (o altres opcions) i sprites coleccionables (estrelles, monedes o similars)
- [ ] Activar física Arcade o qualsevol altre física. Gestionar les colisions
- [ ] Afegir jugador amb un Sprite. Utilitzar animacions per als moviments i salts, així com altres efectes com fonts de particules
- [ ] Utilitzar inputs de teclat. Posar tots els inputs en una funció inputs. 
- [ ] Afegir input Joystick Virtual Touchable per a mòbils
- [ ] Crear un Score on mostrar els punts i les vides restants
- [ ] Crear un sprite enemic amb el qual al col·lisionar es perd una vida. Reiniciar el joc automàticament al morir excepte si s'han acabat les vides. Mostra Game Over i opció de tornar a començar
- [ ] Afegir comptador de vides però no un text sinó sprite del jugador que mostri quantes vides li queden
- [ ] Afegir efecte al recollir colleccionables
- [ ] Afegir efecte al morir (earthquake, camera shake, particles i so)
- [ ] Afegir sons al saltar, col·lisionar, morir
- [ ] Afegir música de fons, es valorarà que el menu d'arranc tingui apartat opcions que permeti apagar la música
- [ ] Utilitzar la camera per crear un mon més ampli i que el jugador es mogui pel mon
- [ ] Mostrar el nivell en que l'usuari està jugant
- [ ] Adaptar el joc per a mòbils:
-  Responsive Web Design
- Passar a Android amb Apache Cordova o Progressive web apps
- Inputs de mòbil: Joystyck hem comentat en anteriors apartats
- Vegeu Phaser#Mobile
- Vegeu Virtual Game Controller
- [ ] Afegir algun efecte atmosfèric com pluja o neu:
http://phaser.io/examples/v2/particles/snow
- Exemple so de pluja: http://opengameart.org/content/rain-loopable
